{"name": "This test case is to validate error when object values are updated without providing reason", "status": "passed", "description": "This test case is to validate error when object values are updated without providing reason", "start": 1733505207902, "stop": 1733505210708, "uuid": "eb9038bc-a1d0-4494-8c7a-2f7df2bd2f9e", "historyId": "3036115bae602c0742b20145deadaa85", "testCaseId": "5828b5033c655629e157f97e26f1f13c", "fullName": "tests.scenarios.ontology.test_object#test_edit_objects_without_reason", "labels": [{"name": "tag", "value": "edit_objects"}, {"name": "tag", "value": "ontology"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.ontology"}, {"name": "suite", "value": "test_object"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.ontology.test_object"}], "links": [{"type": "link"}]}