{"name": "Test to validate that corrector and reviewer cannot be same user", "status": "passed", "description": "This testcase tests validating error message when corrector and reviewer are same user", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03', 'facility.admin.03']"}], "start": 1733495839535, "stop": 1733495855793, "uuid": "20fc59f4-9dc2-4559-b25c-67110859174a", "historyId": "ceffd67d4e1f94f2e1dde03c4e710905", "testCaseId": "9be833f4670b8cb7938be25a4943016c", "fullName": "tests.scenarios.job.test_correction_execution.TestCorrectionExecution#test_validate_error_with_same_reviewer_and_corrector", "labels": [{"name": "tag", "value": "test_validate_error_with_same_reviewer_and_corrector"}, {"name": "tag", "value": "test_enable_corrections"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_correction_execution"}, {"name": "subSuite", "value": "TestCorrectionExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_correction_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvcvxpm", "name": "https://app.clickup.com/t/86cvcvxpm"}]}