{"name": "Test to create a scheduler with without due after", "status": "passed", "description": "This test case validates scheduler with validation error on due after", "start": 1733747386229, "stop": 1733747393707, "uuid": "c78a7d90-5cf8-428e-8b1f-efa3465240aa", "historyId": "35efbfe33cb6d7bf72c7ea251e5c8502", "testCaseId": "26be945865347923ed7eaf71fc47683c", "fullName": "tests.scenarios.test_create_schedulers.TestCreateScheduler#test_validate_error_with_invalid_date_on_scheduler", "labels": [{"name": "tag", "value": "validate_error_with_invalid_date_on_scheduler"}, {"name": "tag", "value": "scheduler"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios"}, {"name": "suite", "value": "test_create_schedulers"}, {"name": "subSuite", "value": "TestCreateScheduler"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "49291-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.test_create_schedulers"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cu3nuxt", "name": "https://app.clickup.com/t/86cu3nuxt"}]}