{"name": "Test to repeat task when subsequent task is stated", "status": "passed", "description": "This test case validates error when user tries to repeat task without completing subsequent task", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733764016343, "stop": 1733764028782, "uuid": "9218b490-8697-44fe-930d-7f90cb6fe6c7", "historyId": "f00fedd43970b230a3579ec747ce3124", "testCaseId": "b43cbf6365470d155b56a9398e59533d", "fullName": "tests.scenarios.job.test_repeat_task.TestRepeatTask#test_error_repeating_task_without_completing_subsequent_task", "labels": [{"name": "tag", "value": "error_repeating_task_without_completing_subsequent_task"}, {"name": "tag", "value": "repeat_task"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_repeat_task"}, {"name": "subSuite", "value": "TestRepeatTask"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_repeat_task"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvw0yfm", "name": "https://app.clickup.com/t/86cvw0yfm"}]}