{"name": "Test to validate the error when user start the job by executing the task having task executor lock configured", "status": "passed", "description": "This test case tests the error when user start the job by executing the task having task executor lock configured", "parameters": [{"name": "job_execution_by", "value": "'user'"}, {"name": "users_list", "value": "['process.publisher.03']"}], "start": 1733767768869, "stop": 1733767778461, "uuid": "5ae39bad-6837-4756-a47a-1dfbaad6c6e7", "historyId": "74f28160e00977d2957fe999ed4b93ec", "testCaseId": "b482d29b6f5ba67216514d6428818d5b", "fullName": "tests.scenarios.job.test_task_executor_lock_execution.TestTaskExecutorLockExecution#test_start_job_by_executing_task_with_task_executor_lock", "labels": [{"name": "tag", "value": "start_job_by_executing_task_with_task_executor_lock"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_task_executor_lock_execution"}, {"name": "subSuite", "value": "TestTaskExecutorLockExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "53959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_task_executor_lock_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cv3brpf", "name": "https://app.clickup.com/t/86cv3brpf"}]}