{"name": "Test to verify that user gets an error when criteria type validation on a number parameter is breached with a least count parameterized value", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_number_parameter_exception_management_execution.TestNumberParameterExceptionManagementExecution object at 0x7af8221a6c30>\nuser_group_creation = 'Auto_Test_user_group_TestNumberParameterExceptionManagementExecution_760', job_execution_by = 'user_group', users_list = []\n\n    @allure.title(\"Test to verify that user gets an error when criteria type validation on a number parameter is \"\n                  \"breached with a least count parameterized value\")\n    @allure.description(\n        \"This test case validates the defined error when criteria type validation with parameterized value \"\n        \"is breached with least count parameterized value\")\n    @allure.link(\"https://app.clickup.com/t/86cvzp1ec\")\n    @pytest.mark.scenario\n    @pytest.mark.job\n    @pytest.mark.exception_management_workflow\n    @pytest.mark.validate_number_param_error_on_criteria_validation_with_least_count_parameterized_value\n    @pytest.mark.parametrize(\"job_execution_by, users_list\", [(\"user\", [Env.get_env_data(\"QA_PUBLISHER_USERNAME_01\")]),\n                                                              (\"user_group\", [])])\n    def test_validate_number_param_error_on_criteria_validation_with_least_count_parameterized_value(self,\n                                                                                                     user_group_creation,\n                                                                                                     job_execution_by,\n                                                                                                     users_list):\n>       process_data = self.process_obj.test_add_number_parameter_with_criteria_type_validation_halt_parameter_condition_and_least_count_parameterized_value()\n\ntests/scenarios/job/test_number_parameter_exception_management_execution.py:412: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/scenarios/test_number_parameter_exception_management.py:669: in test_add_number_parameter_with_criteria_type_validation_halt_parameter_condition_and_least_count_parameterized_value\n    validate_checklist()\ntests/unit/prototyping/process.py:186: in validate_checklist\n    status_200(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>, message = ''\n\n    def status_200(response, message=None):\n        if message is None:\n            message = response.text\n>       assert response.status_code == 200, message\nE       AssertionError\n\nutil/validate_response.py:4: AssertionError"}, "description": "This test case validates the defined error when criteria type validation with parameterized value is breached with least count parameterized value", "parameters": [{"name": "job_execution_by", "value": "'user_group'"}, {"name": "users_list", "value": "[]"}], "start": 1733499682397, "stop": 1733499683951, "uuid": "54956a09-d425-43b3-aceb-8ea2a735480d", "historyId": "2f51a5befed2c02da70df1ab6ca343e5", "testCaseId": "54df65dc6469f666cb514e551180a7f5", "fullName": "tests.scenarios.job.test_number_parameter_exception_management_execution.TestNumberParameterExceptionManagementExecution#test_validate_number_param_error_on_criteria_validation_with_least_count_parameterized_value", "labels": [{"name": "tag", "value": "validate_number_param_error_on_criteria_validation_with_least_count_parameterized_value"}, {"name": "tag", "value": "exception_management_workflow"}, {"name": "tag", "value": "job"}, {"name": "tag", "value": "scenario"}, {"name": "parentSuite", "value": "tests.scenarios.job"}, {"name": "suite", "value": "test_number_parameter_exception_management_execution"}, {"name": "subSuite", "value": "TestNumberParameterExceptionManagementExecution"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "29333-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.scenarios.job.test_number_parameter_exception_management_execution"}], "links": [{"type": "link", "url": "https://app.clickup.com/t/86cvzp1ec", "name": "https://app.clickup.com/t/86cvzp1ec"}]}